name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run tests and generate coverage report
        run: |
          python -m pytest -v --cov=/workspaces/Chibundu_week1-devopss/tests/
          coverage xml -o coverage.xml

      # Add coverage report as comment in pull request
      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
            pytest-coverage-path: coverage.xml
