name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest -v tests
          pytest --cov=my_project tests/
          coverage xml -o coverage.xml

      # Add coverage report as comment in pull request
      - name: Add coverage report as comment
        uses: macropin/pytest-cov-comment@v2
        with:
          github_token: ${{ secrets.DEVOPSWEEK1_TOKEN }}
          coverage_file: coverage.xml

